- type: job
  id: Magistrat
  name: job-name-magistrat
  description: job-description-magistrat
  playTimeTracker: JobMagistrat
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelistRequired: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 180000 #50 hrs
    - !type:RoleTimeRequirement
      role: JobIAA
      time: 90000 #25 hrs
  startingGear: MagistratGear
  icon: "JobIconMagistrat"
  supervisors: job-supervisors-service
  canBeAntag: false
  setPreference: true
  access:
  - Magistrat
  - Bar
  - Kitchen
  - Hydroponics
  - Janitor
  - Theatre
  - Chapel
  - Lawyer
  - Brig
  - Security
  - Medical
  - Research
  - Engineering
  - Cargo
  - Salvage
  - Command
  - CentralCommand
  - CCSecurity
  - CCOfficer
  extendedAccess:
  - Hydroponics
  minBankBalance: 200
  maxBankBalance: 300
  wageDepartment: CentCom
  wage: 80
  special:
  - !type:AddComponentSpecial
    components:
      - type: PsionicBonusChance
        flatBonus: 0.025
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: MagistratGear
  equipment:
    jumpsuit: MagistratUniformSuit
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingMagistrateroba
    id: MagistratPDA
    ears: ClothingHeadsetAltCommand
    head: ClothingHeadHatPwig
    neck: ClothingNeckLawyerbadge
    pocket1: Flash
    pocket2: RubberStampCentcom
#    inhand: - BriefcasemagistratFilled black magistrate's suitcase in development
  inhand:
    - BriefcaseIAAFilled
  innerClothingSkirt: MagistratUniformSuit
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
